name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run build
      - name: Copy build artifacts
        uses: appleboy/scp-action@v0.1.3
        with:
          host: "93.188.164.152"
          username: "root"
          port: "22"
          key: ${{ secrets.SSHKEY }}
          source: "dist/."
          target: "/home/thetufan/htdocs/www.thetufan.com"
